# Generated by Django 2.2.6 on 2019-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomled', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP address')),
                ('port', models.IntegerField(verbose_name='port')),
                ('leds', models.IntegerField(verbose_name='leds')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('inverted', models.BooleanField(verbose_name='inverted')),
            ],
        ),
    ]
